export default {
  SET_THEME: 'SET_THEME',
  CREATE_TODO: 'CREATE_TODO',
  CREATE_TASK: 'CREATE_TASK',
  OPEN_CREATOR: 'OPEN_CREATOR',
  CLOSE_CREATOR: 'CLOSE_CREATOR',
  SET_ACTIVE_TASK: 'SET_ACTIVE_TASK',
  DELETE_TASK: 'DELETE_TASK',
}
