export default {
  SET_DATA: 'SET_DATA',
  UPDATE_LOCALSTORAGE: 'UPDATE_LOCALSTORAGE',
  SET_THEME: 'SET_THEME',
  CREATE_TODO: 'CREATE_TODO',
  EDIT_TODO_LIST: 'EDIT_TODO_LIST',
  DELETE_TODO_LIST: 'DELETE_TODO_LIST',
  SET_ACTIVE_TASK: 'SET_ACTIVE_TASK',
  CREATE_TASK: 'CREATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  OPEN_CREATOR: 'OPEN_CREATOR',
  CLOSE_CREATOR: 'CLOSE_CREATOR',
}
